version: '3'
services:
  app:
    image: mcr.microsoft.com/devcontainers/universal:2
    volumes:
      - .:/workspace
    ports:
      - 5000:5000
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: neowflteam
      POSTGRES_PASSWORD: Qa1Ol0Sx2Km8
      POSTGRES_DB: TestingDB
    ports:
      - 5432:5432